name: Build
on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false
      - name: docker build
        run: ./build.sh
      - name: docker login
        run: docker login --username ${{secrets.DOCKERHUB_USERNAME}} --password ${{secrets.DOCKERHUB_TOKEN}}
        if: github.ref == 'refs/heads/master'
      - name: docker push
        run: ./push.sh
        if: github.ref == 'refs/heads/master'
